spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=prefer'
    username: risk_profiler
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:/db/migration/postgres,classpath:/db/migration/common
    url: ${spring.datasource.url}
    user: ${SUPERUSER_USERNAME}
    password: ${SUPERUSER_PASSWORD}
    placeholders.database_password: ${DATABASE_PASSWORD}
    schemas: risk_profiler
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

graceful:
  shutdown:
    enabled: true
