info:
  app:
     name: Offender Risk Profiler API

spring:
  application:
    name: offender-risk-profiler-api

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS : false

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    baselineOnMigrate: true

  datasource:
    url: 'jdbc:h2:mem:risk-profiler-db;MODE=PostgreSQL'
    continue-on-error: true

    hikari:
      pool-name: RiskProfiler-CP
      connectionTimeout: 1000
      validationTimeout:  500

server:
  port: 8080
  servlet:
    context-path: /
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.digital: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

elite2api:
  client:
    clientId: ${risk.profiler.client.id}
    clientSecret: ${risk.profiler.client.secret}
    accessTokenUri: ${nomis.auth.url}
    tokenName: elite2_token
    authenticationScheme: header
    clientAuthenticationScheme: header
