version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2

executors:
  java-machine:
    machine:
#      TODO: this should be upgraded as soon as a java 16 machine image is available,
#        see https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202104-01
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.jvmargs=-XX:+UseContainerSupport -Dkotlin.compiler.execution.strategy=in-process
    working_directory: ~/app

jobs:
  validate:
    executor: java-machine
    steps:
      - checkout
      - hmpps/install_aws_cli
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
#      - run:
#          name: Wait for SQS to be ready
#          command: curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://localhost:4576
#      - run:
#          name: Set up queues
#          command: src/test/resources/localstack/setup-sns.sh
      - run:
          command: docker run -p6379:6379 --env ALLOW_EMPTY_PASSWORD=yes redis
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
          requires:
            - validate
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - helm_lint
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - offender-risk-profiler-preprod
            - hmpps-common-vars
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context:
            - offender-risk-profiler-prod
            - hmpps-common-vars
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
