---
generic-service:
  nameOverride: offender-risk-profiler
  productId: "DPS006"

  image:
    repository: quay.io/hmpps/offender-risk-profiler
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: offender-risk-profiler-cert

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "s3,postgres,sqs"
    CACHE_TYPE: "elasticache"
    SPRING_REDIS_SSL: "true"

  namespace_secrets:
    rp-sqs-instance-output:
      HMPPS_SQS_QUEUES_RISKPROFILERCHANGEQUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_RISKPROFILERCHANGEQUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_RISKPROFILERCHANGEQUEUE_QUEUE_NAME: "sqs_rpc_name"
    oc-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_EVENTS_QUEUE_NAME: "sqs_oce_name"
    dps-rds-instance-output:
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_PASSWORD: "risk_profiler_password"
      SUPERUSER_USERNAME: "database_username"
      SUPERUSER_PASSWORD: "database_password"
    offender-risk-profiler:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RISK_PROFILER_CLIENT_ID: "RISK_PROFILER_CLIENT_ID"
      RISK_PROFILER_CLIENT_SECRET: "RISK_PROFILER_CLIENT_SECRET"
    risk-profiler-s3-bucket-output:
      S3_BUCKET_NAME: "bucket_name"
    oc-elasticache-redis:
      SPRING_REDIS_HOST: "primary_endpoint_address"
      SPRING_REDIS_PASSWORD: "auth_token"

  resources:
    requests:
      cpu: 10m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 1000Mi

generic-prometheus-alerts:
  targetApplication: offender-risk-profiler
