---
generic-service:
  nameOverride: offender-risk-profiler
  serviceAccountName: offender-risk-profiler
  productId: "DPS006"

  image:
    repository: quay.io/hmpps/offender-risk-profiler
    tag: latest
    pullPolicy: IfNotPresent
    port: 8080

  ingress:
    enabled: true
    modsecurity_enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
    tlsSecretName: offender-risk-profiler-cert

  allowlist:
    cloudplatform-live1-1: 35.178.209.113/32
    cloudplatform-live1-2: 3.8.51.207/32
    cloudplatform-live1-3: 35.177.252.54/32
    health-kick: 35.177.252.195/32
    global-protect: 35.176.93.186/32
    mojvpn: 81.134.202.29/32
    office: 217.33.148.210/32

  livenessProbe:
    httpGet:
      path: /ping
      port: http
    periodSeconds: 30
    initialDelaySeconds: 90
    timeoutSeconds: 20
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /ping
      port: http
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  env:
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: "s3,postgres,sqs"
    CACHE_TYPE: "elasticache"
    SPRING_REDIS_SSL: "true"
    AWS_REGION: "eu-west-2"

  namespace_secrets:
    dps-rds-instance-output:
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_PASSWORD: "risk_profiler_password"
      SUPERUSER_USERNAME: "database_username"
      SUPERUSER_PASSWORD: "database_password"

    offender-risk-profiler:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RISK_PROFILER_CLIENT_ID: "RISK_PROFILER_CLIENT_ID"
      RISK_PROFILER_CLIENT_SECRET: "RISK_PROFILER_CLIENT_SECRET"

    risk-profiler-s3-bucket-output:
      S3_BUCKET_NAME: "bucket_name"

    rp-sqs-instance-output:
      SQS_RPC_QUEUE_URL: "sqs_rpc_url"

    oc-events-sqs-instance-output:
      SQS_EVENTS_QUEUE_NAME: "sqs_oce_name"

    oc-events-sqs-dl-instance-output:
      SQS_EVENTS_DLQ_QUEUE_NAME: "sqs_oce_name"

    oc-elasticache-redis:
      SPRING_REDIS_HOST: "primary_endpoint_address"
      SPRING_REDIS_PASSWORD: "auth_token"

  resources:
    requests:
      cpu: 10m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 1000Mi

generic-prometheus-alerts:
  targetApplication: offender-risk-profiler
