---
generic-service:

  replicaCount: 2

  env:
    NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    ELITE2API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk
    PATHFINDERAPI_ENDPOINT_URL: https://dev-api.pathfinder.service.justice.gov.uk

  ingress:
    host: offender-risk-profiler-dev.hmpps.service.justice.gov.uk

  namespace_secrets:
    rp-sqs-instance-output:
      HMPPS_SQS_QUEUES_RISKPROFILERCHANGE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_RISKPROFILERCHANGE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_RISKPROFILERCHANGE_QUEUE_NAME: "Digital-Prison-Services-dev-risk_profiler_change"
    oc-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_EVENTS_QUEUE_NAME: "Digital-Prison-Services-dev-offender_categorisation_events_queue"
    oc-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_EVENTS_DLQ_ACCESS_KEY_ID: "dlq_access_key_id"
      HMPPS_SQS_QUEUES_EVENTS_DLQ_SECRET_ACCESS_KEY: "dlq_secret_access_key"
      HMPPS_SQS_QUEUES_EVENTS_DLQ_NAME: "Digital-Prison-Services-dev-offender_categorisation_events_queue_dl"

  # CloudPlatform AlertManager receiver to route prometheus alerts to slack
  # See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
  generic-prometheus-alerts:
    alertSeverity: digital-prison-service-dev