---
generic-service:

  replicaCount: 2

  env:
    NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    ELITE2API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk
    PATHFINDERAPI_ENDPOINT_URL: https://dev-api.pathfinder.service.justice.gov.uk
    PRISONER_ALERTS_API_ENDPOINT_URL: https://alerts-api-dev.hmpps.service.justice.gov.uk

  ingress:
    host: offender-risk-profiler-dev.hmpps.service.justice.gov.uk

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: dps-sed-alerts-nonprod
