---
generic-service:

  replicaCount: 2

  env:
    NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    ELITE2API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk
    PATHFINDERAPI_ENDPOINT_URL: https://dev-api.pathfinder.service.justice.gov.uk
