# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/offender-risk-profiler
  tag: latest
  pullPolicy: IfNotPresent
  port: 8080

env:
  NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  ELITE2API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk
  PATHFINDERAPI_ENDPOINT_URL: https://dev-api.pathfinder.service.justice.gov.uk
