---
generic-service:

  replicaCount: 4

  env:
    NOMIS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    ELITE2API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
    PATHFINDERAPI_ENDPOINT_URL: https://preprod-api.pathfinder.service.justice.gov.uk

